server:
  applicationConnectors:
    - type: http
      port: 8989
      bindHost: 0.0.0.0
  adminConnectors:
    - type: http
      port: 8990
      bindHost: 0.0.0.0

graphhopper:
  # No data reader file specified - will require manual data import
  datareader.file: ""
  # Local folder used by graphhopper to store its data
  graph.location: graph-cache
  
  # Basic routing profiles
  profiles:
    - name: car
      vehicle: car
      weighting: fastest
      turn_costs: false

  # Import settings
  graph.flag_encoders: car
  graph.dataaccess: RAM_STORE

  # Web settings
  web:
    bind_host: 0.0.0.0
    port: 8989

# Logging configuration
logging:
  level: INFO
  loggers:
    com.graphhopper: INFO
    "org.eclipse.jetty": WARN
  appenders:
    - type: console
      logFormat: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"