name: Cache Cleanup

on:
  schedule:
    - cron: '0 2 * * 0' # Every Sunday at 2am
  workflow_dispatch:

jobs:
  cleanup-caches:
    if: github.repository_owner == 'xanox-org'
    runs-on: self-hosted
    permissions:
      actions: write
    steps:
      - name: Cleanup old GitHub Actions caches
        run: |
          echo "Cleaning up old GitHub Actions caches..."
          # Keep caches from last 7 days
          gh api repos/${{ github.repository }}/actions/caches \
            --jq '.actions_caches[] | select(.created_at < (now - 604800 | strftime("%Y-%m-%dT%H:%M:%SZ"))) | .id' \
            | xargs -I {} gh api repos/${{ github.repository }}/actions/caches/{} -X DELETE \
            || echo "Cache cleanup completed with possible warnings"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cleanup Docker images on self-hosted runner
        run: |
          echo "Cleaning up Docker images..."
          # Remove unused images older than 7 days
          docker image prune -a -f --filter "until=168h" || echo "Docker cleanup completed"

          # Clean up dangling images
          docker image prune -f || echo "Dangling images cleanup completed"

          # Clean up unused volumes
          docker volume prune -f || echo "Volume cleanup completed"

      - name: Cleanup Maven local repository
        run: |
          echo "Cleaning up Maven repository..."
          # Remove old snapshots and temporary files
          find ~/.m2/repository -name "*SNAPSHOT*" -type d -mtime +7 -exec rm -rf {} + 2>/dev/null || echo "SNAPSHOT cleanup completed"
          find ~/.m2/repository -name "_remote.repositories" -mtime +14 -delete 2>/dev/null || echo "Remote repos cleanup completed"
          find ~/.m2/repository -name "resolver-status.properties" -mtime +14 -delete 2>/dev/null || echo "Resolver status cleanup completed"

      - name: Cleanup npm cache
        run: |
          echo "Cleaning up npm cache..."
          npm cache clean --force 2>/dev/null || echo "npm cache cleanup completed"

      - name: Report cleanup status
        run: |
          echo "=== Cleanup Summary ==="
          echo "Docker images:"
          docker images --format "table {{.Repository}}\t{{.Tag}}\t{{.Size}}\t{{.CreatedAt}}" | head -10
          echo ""
          echo "Maven repository size:"
          du -sh ~/.m2/repository 2>/dev/null || echo "Maven repository not found"
          echo ""
          echo "Available disk space:"
          df -h /