name: Publish to GitHub Packages

# ignore tags as the untagged commit has the same GITHUB_SHA and would conflict
on:
  push:
    branches:
    - '**'

jobs:
  publish:
    if: github.repository_owner == 'xanox-org'
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      # Enhanced caching for publishing workflow
      - name: Cache Maven repository
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            ~/.m2/wrapper
            ~/.m2/.offline-cache
          key: ${{ runner.os }}-maven-publish-17-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-publish-17-
            ${{ runner.os }}-maven-prod-17-
            ${{ runner.os }}-maven-

      - name: Cache Node.js installation
        uses: actions/cache@v4
        with:
          path: web-bundle/node
          key: ${{ runner.os }}-node-v20.14.0-${{ hashFiles('web-bundle/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-node-v20.14.0-
            ${{ runner.os }}-node-

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: |
            web-bundle/node_modules
            ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('web-bundle/package-lock.json', 'web-bundle/package.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-${{ hashFiles('web-bundle/package-lock.json') }}
            ${{ runner.os }}-npm-

      # Cache build artifacts for faster publishing
      - name: Cache compilation artifacts
        uses: actions/cache@v4
        with:
          path: |
            **/target/classes
            **/target/test-classes
            **/target/generated-sources
          key: ${{ runner.os }}-publish-artifacts-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-artifacts-${{ github.sha }}
            ${{ runner.os }}-publish-artifacts-
            ${{ runner.os }}-build-artifacts-

      # Optimized dependency resolution
      - name: Resolve dependencies offline
        run: |
          mvn dependency:go-offline -B -q || echo "Some dependencies may not be available offline"
          mvn dependency:resolve-sources -B -q || echo "Source resolution completed"

      - name: Build and publish package with optimizations
        # special 'wagon' option due to https://github.com/orgs/community/discussions/49001
        run: |
          mvn -B versions:set -DnewVersion=$GITHUB_SHA -DgenerateBackupPoms=false
          mvn -Dmaven.resolver.transport=wagon \
              -B -DskipTests \
              -Pskip-shaded-web-jar -Pskip-tools-jar \
              -T 2C \
              -Dmaven.compile.fork=true \
              -Dmaven.compiler.maxmem=2048m \
              source:jar deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
